services:
  - type: web
    name: dashboard-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: |
      php artisan migrate:fresh --seed --force
      php artisan serve --host=0.0.0.0 --port=${PORT:-8080}