services:
  - type: web
    name: dashboard-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=8080"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: "base64:cIftllNdhRXMNJUqvX6J4t+4EnA/k+8H/SVgVmIChQA="
